//
//  ComponentsLibrary.swift
//  Components
//
//  Storage for components list
// 
//  Created by Lasitha Weligampola on 2024-03-08.
//

import Foundation

struct ComponentsManager {
    static let list =  [
        Component(name: "Text", type: .textInOut, icon: "text.aligncenter",
                  description: "Displays a single line of non-editable, formatted text.",
                  link: "https://developer.apple.com/documentation/swiftui/text/"),
        Component(name: "Label", type: .textInOut, icon: "tag",
                  description: "A view that displays a text string and can optionally associate itself with another view for accessibility purposes.",
                  link: "https://developer.apple.com/documentation/swiftui/Label/"),
        Component(name: "TextField", type: .textInOut, icon: "character.textbox",
                  description: "A single-line editable text input field",
                  link: "https://developer.apple.com/documentation/swiftui/TextField"),
        Component(name: "SecureField", type: .textInOut, icon: "lock",
                  description: "Similar to TextField but hides the entered text with dots for password input.",
                  link: "https://developer.apple.com/documentation/swiftui/SecureField"),
        Component(name: "TextArea", type: .textInOut, icon: "doc.text",
                  description: "A multi-line editable text input field for longer content.",
                  link: "https://developer.apple.com/documentation/swiftui/TextEditor"),
        Component(name: "Image", type: .textInOut, icon: "photo",
                  description: "Displays an image from an asset or URL.",
                  link: "https://developer.apple.com/documentation/swiftui/Image"),
        Component(name: "Button", type: .controls, icon: "button.horizontal",
                  description: "A clickable element that triggers an action when pressed.",
                  link: "https://developer.apple.com/documentation/swiftui/Button"),
        Component(name: "Menu", type: .controls, icon: "filemenu.and.selection",
                  description: "A control that displays a list of options when tapped.",
                  link: "https://developer.apple.com/documentation/swiftui/Menu"),
        Component(name: "Link", type: .controls, icon: "link",
                  description: "Text that, when tapped, opens a URL or performs a custom action.",
                  link: "https://developer.apple.com/documentation/swiftui/Link"),
        Component(name: "Slider", type: .controls, icon: "slider.horizontal.3",
                  description: "A control that allows users to select a value from a continuous range using a draggable thumb.",
                  link: "https://developer.apple.com/documentation/swiftui/Slider"),
        Component(name: "Stepper", type: .controls, icon: "plusminus.circle",
                  description: "A control that increments or decrements a value by tapping buttons.",
                  link: "https://developer.apple.com/documentation/swiftui/Stepper"),
        Component(name: "Toggle", type: .controls, icon: "togglepower",
                  description: "A switch-like control that can be turned on or off.",
                  link: "https://developer.apple.com/documentation/swiftui/Toggle"),
        Component(name: "Picker", type: .controls, icon: "hand.point.up.braille.fill",
                  description: "A control that allows users to select a value from a predefined list.",
                  link: "https://developer.apple.com/documentation/swiftui/Picker"),
        Component(name: "DatePicker", type: .controls, icon: "calendar",
                  description: "A control for selecting a date or time.",
                  link: "https://developer.apple.com/documentation/swiftui/DatePicker"),
        Component(name: "ColorPicker", type: .controls, icon: "eyedropper",
                  description: "A control for selecting a color from a predefined palette or custom color space.",
                  link: "https://developer.apple.com/documentation/swiftui/ColorPicker"),
        Component(name: "ProgressView", type: .controls, icon: "chart.bar",
                  description: "A visual indicator of the progress of an operation.",
                  link: "https://developer.apple.com/documentation/swiftui/ProgressView"),
        Component(name: "HStack", type: .containerViews, icon: "lines.measurement.horizontal",
                  description: "A horizontal stack layout that arranges views side-by-side. Made scrollable to accommodate more than 10 items.",
                  link: "https://developer.apple.com/documentation/swiftui/HStack"),
        Component(name: "VStack", type: .containerViews, icon: "lines.measurement.vertical",
                  description: "A vertical stack layout that arranges views one above the other. Made scrollable to accommodate more than 10 items.",
                  link: "https://developer.apple.com/documentation/swiftui/VStack"),
        Component(name: "ZStack", type: .containerViews, icon: "square.stack.3d.up.fill",
                  description: "A view that stacks multiple views on top of each other, with the last added view appearing on top.",
                  link: "https://developer.apple.com/documentation/swiftui/ZStack"),
        Component(name: "Form", type: .containerViews, icon: "pencil.and.list.clipboard",
                  description: "A container view that groups controls and labels for data entry with a specific style.",
                  link: "https://developer.apple.com/documentation/swiftui/Form"),
        Component(name: "NavigationView", type: .containerViews, icon: "chevron.left.2",
                  description: "A container view that provides navigation features within an application, typically used for hierarchical navigation structures.",
                  link: "https://developer.apple.com/documentation/swiftui/NavigationView"),
        Component(name: "Alerts", type: .containerViews, icon: "exclamationmark.triangle",
                  description: "A modal dialog that presents a message to the user, often with one or more buttons for responding",
                  link: "https://developer.apple.com/documentation/swiftui/Alert"),
        Component(name: "Sheets", type: .containerViews, icon: "rectangle.and.pencil.and.ellipsis",
                  description: "A sheet-like modal view that slides up from the bottom of the screen.",
                  link: "https://developer.apple.com/documentation/swiftui/view/sheet(ispresented:ondismiss:content:)"),
        Component(name: "Plain", type: .list, icon: "square",
                  description: "A basic list view that displays a single line of text for each item.",
                  link: "https://developer.apple.com/documentation/swiftui/liststyle/plain"),
        Component(name: "Inset", type: .list, icon: "rectangle.inset.filled",
                  description: "A list style with slight insets around each item for visual separation.",
                  link: "https://developer.apple.com/documentation/swiftui/liststyle/Inset"),
        Component(name: "Grouped", type: .list, icon: "square.grid.2x2",
                  description: "A list style that groups items together based on a common header.",
                  link: "https://developer.apple.com/documentation/swiftui/liststyle/Grouped"),
        Component(name: "Inset Grouped", type: .list, icon: "square.grid.3x1.below.line.grid.1x2",
                  description: "A grouped list style with slight insets around each item within a group for better visual hierarchy.",
                  link: "https://developer.apple.com/documentation/swiftui/liststyle/insetgrouped"),
        Component(name: "Sidebar", type: .list, icon: "sidebar.left",
                  description: "A two-column list style where a sidebar on the left remains visible while the main content area scrolls on the right.",
                  link: "https://developer.apple.com/documentation/swiftui/liststyle/sidebar"),
    ]
}
